"""Remove models, leave user model

Revision ID: 05748cdd7dd1
Revises: 0fa47de907b6
Create Date: 2024-08-01 10:23:13.563984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05748cdd7dd1'
down_revision = '0fa47de907b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grant')
    op.drop_table('grant_answer')
    op.drop_table('grant_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('grant_id', sa.INTEGER(), nullable=False),
    sa.Column('grant_question', sa.VARCHAR(length=200), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_question')
    )
    op.create_table('grant_answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('grant_id', sa.INTEGER(), nullable=False),
    sa.Column('grant_question_id', sa.INTEGER(), nullable=False),
    sa.Column('grant_answer', sa.VARCHAR(length=300), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grant.id'], ),
    sa.ForeignKeyConstraint(['grant_question_id'], ['grant_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_answer')
    )
    op.create_table('grant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('fund', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('fund'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
