"""empty message

Revision ID: 17bde4ed73cc
Revises: e43b6c754da0
Create Date: 2024-08-27 17:40:50.315118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bde4ed73cc'
down_revision = 'e43b6c754da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'grant_application', ['application_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('application_id')

    # ### end Alembic commands ###
