"""add `is_approved` and `is_rejected` fields to GrantApplication Model

Revision ID: 1f537ac9fcfd
Revises: 244ce8875092
Create Date: 2024-09-01 20:27:34.801202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f537ac9fcfd'
down_revision = '244ce8875092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_rejected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant_application', schema=None) as batch_op:
        batch_op.drop_column('is_rejected')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
