"""empty message

Revision ID: 24fbf7590742
Revises: bdd8261021d8
Create Date: 2024-08-05 15:50:56.235512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fbf7590742'
down_revision = 'bdd8261021d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=300), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grant_question_id'], ['grant_question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grant_answer')
    # ### end Alembic commands ###
