"""Initial migration.

Revision ID: 30dd99ec2bf1
Revises: 
Create Date: 2024-08-01 09:42:20.802172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dd99ec2bf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('fund', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('fund'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('grant_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('grant_question', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_question')
    )
    op.create_table('grant_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grant_id', sa.Integer(), nullable=False),
    sa.Column('grant_question_id', sa.Integer(), nullable=False),
    sa.Column('grant_answer', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grant.id'], ),
    sa.ForeignKeyConstraint(['grant_question_id'], ['grant_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_answer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grant_answer')
    op.drop_table('grant_question')
    op.drop_table('user')
    op.drop_table('grant')
    # ### end Alembic commands ###
