"""empty message

Revision ID: 796159d40fdc
Revises: 
Create Date: 2024-08-28 21:37:54.528311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796159d40fdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('user_type', sa.Enum('GRANTEE', 'GRANTER', name='usertype'), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grant_title', sa.String(length=200), nullable=False),
    sa.Column('grant_description', sa.String(length=200), nullable=False),
    sa.Column('grant_fund', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_title')
    )
    op.create_table('grant_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grant_id', sa.Integer(), nullable=True),
    sa.Column('application_status', sa.Enum('APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['grant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grant_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('grant_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['grant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grant_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('grant_question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=300), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['grant_application.id'], ),
    sa.ForeignKeyConstraint(['grant_question_id'], ['grant_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grant_answer')
    op.drop_table('grant_question')
    op.drop_table('grant_application')
    op.drop_table('grant')
    op.drop_table('user')
    # ### end Alembic commands ###
