"""empty message

Revision ID: 8a9df5acf5f8
Revises: 1f537ac9fcfd
Create Date: 2024-09-04 17:09:44.849193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9df5acf5f8'
down_revision = '1f537ac9fcfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
